-- configure vraibles 
SET TEAM_ROLE = 'DEC';
SET TEAMMATE1_USER = 'ANTONI';
SET TEAMMATE1_PASSWORD = 'spain';
SET TEAMMATE2_USER = 'GRAHAM';
SET TEAMMATE2_PASSWORD = 'scotland';
SET MY_WAREHOUSE = 'AIRBYTE_WAREHOUSE';
SET MY_DATABASE = 'AIRBYTE_DATABASE';
SET RAW_SCHEMA = 'AIRBYTE_RAW_DATA';
SET ANALYTICS_SCHEMA = 'ANALYTICS';
SET RAW_FULL_SCHEMA_NAME = $MY_DATABASE || '.' || $RAW_SCHEMA;

USE ROLE ACCOUNTADMIN;

-- creates team role
CREATE ROLE IF NOT EXISTS IDENTIFIER($TEAM_ROLE);
GRANT ROLE IDENTIFIER($TEAM_ROLE) TO ROLE SYSADMIN;

-- create db and schema
CREATE DATABASE IF NOT EXISTS IDENTIFIER($MY_DATABASE);
USE DATABASE IDENTIFIER($MY_DATABASE);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($RAW_SCHEMA);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($ANALYTICS_SCHEMA);

-- create user for antoni
CREATE USER IF NOT EXISTS IDENTIFIER($TEAMMATE1_USER)
    PASSWORD = $TEAMMATE1_PASSWORD
    LOGIN_NAME = $TEAMMATE1_USER
    DISPLAY_NAME = $TEAMMATE1_USER
    DEFAULT_WAREHOUSE = $MY_WAREHOUSE
    DEFAULT_ROLE = $TEAM_ROLE
    DEFAULT_NAMESPACE = $MY_DATABASE || '.' || $ANALYTICS_SCHEMA -- Default to analytics schema
    MUST_CHANGE_PASSWORD = TRUE;

-- create user for graham
CREATE USER IF NOT EXISTS IDENTIFIER($TEAMMATE2_USER)
    PASSWORD = $TEAMMATE2_PASSWORD
    LOGIN_NAME = $TEAMMATE2_USER
    DISPLAY_NAME = $TEAMMATE2_USER
    DEFAULT_WAREHOUSE = $MY_WAREHOUSE
    DEFAULT_ROLE = $TEAM_ROLE
    DEFAULT_NAMESPACE = $MY_DATABASE || '.' || $ANALYTICS_SCHEMA -- Default to analytics schema
    MUST_CHANGE_PASSWORD = TRUE;

-- Grants access to the AB warehouse
GRANT USAGE ON WAREHOUSE IDENTIFIER($MY_WAREHOUSE) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT USAGE ON DATABASE IDENTIFIER($MY_DATABASE) TO ROLE IDENTIFIER($TEAM_ROLE); -- gives access to the AB database

-- Grants access to the schema where Airbyte writes data
GRANT USAGE ON SCHEMA IDENTIFIER($RAW_FULL_SCHEMA_NAME) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER($RAW_FULL_SCHEMA_NAME) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($RAW_FULL_SCHEMA_NAME) TO ROLE IDENTIFIER($TEAM_ROLE);

-- Grant usage on the new schema
GRANT USAGE ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);

-- grants create for tables, views, stages, file formats, udfs and sps
GRANT CREATE TABLE ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT CREATE VIEW ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT CREATE STAGE ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT CREATE FILE FORMAT ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT CREATE FUNCTION ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT CREATE PROCEDURE ON SCHEMA IDENTIFIER($ANALYTICS_SCHEMA) TO ROLE IDENTIFIER($TEAM_ROLE);

-- grant role to users
GRANT ROLE IDENTIFIER($TEAM_ROLE) TO USER IDENTIFIER($TEAMMATE1_USER);
GRANT ROLE IDENTIFIER($TEAM_ROLE) TO USER IDENTIFIER($TEAMMATE2_USER);

-- check 
SELECT 'team user and permissions setup complete!' AS Status;
