-- Set context
USE DATABASE AIRBYTE_DATABASE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE AIRBYTE_DATABASE.ANALYTICS.DIM_LOCATION AS
SELECT
    ROW_NUMBER() OVER (ORDER BY A.ADDRESS_ID) AS LOCATION_ID,
    A.ADDRESS_ID, 
    A.ADDRESS,
    A.ADDRESS2,
    A.DISTRICT,
    CI.CITY,
    CO.COUNTRY,
    A.POSTAL_CODE,
    A.PHONE
FROM AIRBYTE_RAW_DATA.ADDRESS A
JOIN AIRBYTE_RAW_DATA.CITY CI ON A.CITY_ID = CI.CITY_ID
JOIN AIRBYTE_RAW_DATA.COUNTRY CO ON CI.COUNTRY_ID = CO.COUNTRY_ID;