-- Crear tabla DIM_FILM sin PRIMARY KEY para evitar problemas
CREATE OR REPLACE TABLE AIRBYTE_DATABASE.ANALYTICS.DIM_FILM (
    FILM_ID INT,
    TITLE STRING,
    RELEASE_YEAR INT,
    LENGTH INT,
    RATING STRING,
    RENTAL_RATE NUMBER(5,2),
    REPLACEMENT_COST NUMBER(6,2),
    CATEGORY STRING
);


