-- Set the context
USE DATABASE AIRBYTE_DATABASE;
USE SCHEMA ANALYTICS;

-- Create fact table
CREATE TABLE IF NOT EXISTS AIRBYTE_DATABASE.ANALYTICS.FACT_RENTAL_SNAPSHOT (
    RENTAL_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    FILM_ID INT,
    DATE_ID INT,
    STAFF_ID INT,
    STORE_ID INT,
    NUM_PAYMENTS INT,
    TOTAL_AMOUNT NUMBER(10,2),
    CUSTOMER_RENTAL_RANK INT,
    RENTAL_DURATION INT
);