USE DATABASE AIRBYTE_DATABASE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE AIRBYTE_DATABASE.ANALYTICS.FACT_PAYMENT AS
SELECT 
    P.PAYMENT_ID,
    P.CUSTOMER_ID,
    R.STAFF_ID,
    I.FILM_ID,
    TO_NUMBER(TO_CHAR(P.PAYMENT_DATE, 'YYYYMMDD')) AS DATE_ID,
    P.AMOUNT,
    P.PAYMENT_DATE
FROM AIRBYTE_RAW_DATA.PAYMENT P
JOIN AIRBYTE_RAW_DATA.RENTAL R ON P.RENTAL_ID = R.RENTAL_ID
JOIN AIRBYTE_RAW_DATA.INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID;
