-- Set context
USE DATABASE AIRBYTE_DATABASE;
USE SCHEMA ANALYTICS;

INSERT INTO AIRBYTE_DATABASE.ANALYTICS.DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(D, 'YYYYMMDD')) AS DATE_ID,
    D AS FULL_DATE,
    DAY(D),
    MONTH(D),
    YEAR(D),
    TRIM(TO_CHAR(D, 'Day')) AS WEEKDAY,
    WEEK(D)
FROM (
    SELECT DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1, COALESCE(MAX_DATE, DATE '2005-01-01')) AS D
    FROM TABLE(GENERATOR(ROWCOUNT => 10000)),
         (SELECT MAX(FULL_DATE) AS MAX_DATE FROM AIRBYTE_DATABASE.ANALYTICS.DIM_DATE)
) AS dates
WHERE D <= CURRENT_DATE
  AND D > COALESCE((SELECT MAX(FULL_DATE) FROM AIRBYTE_DATABASE.ANALYTICS.DIM_DATE), DATE '2005-01-01');
