-- Populate the fact table
-- This performs an incremental load, only inserting new rental records
INSERT INTO AIRBYTE_DATABASE.ANALYTICS.FACT_RENTAL_SNAPSHOT
SELECT * FROM (
  SELECT 
      R.RENTAL_ID,
      R.CUSTOMER_ID,
      I.FILM_ID,
      TO_NUMBER(TO_CHAR(R.RENTAL_DATE, 'YYYYMMDD')) AS DATE_ID,
      R.STAFF_ID,
      I.STORE_ID,
      COUNT(P.PAYMENT_ID) OVER (PARTITION BY R.RENTAL_ID) AS NUM_PAYMENTS,
      SUM(P.AMOUNT) OVER (PARTITION BY R.RENTAL_ID) AS TOTAL_AMOUNT,
      RANK() OVER (PARTITION BY R.CUSTOMER_ID ORDER BY R.RENTAL_DATE) AS CUSTOMER_RENTAL_RANK,
      DATEDIFF(DAY, R.RENTAL_DATE, R.RETURN_DATE) AS RENTAL_DURATION
  FROM AIRBYTE_RAW_DATA.RENTAL R
  JOIN AIRBYTE_RAW_DATA.INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
  LEFT JOIN AIRBYTE_RAW_DATA.PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
) NEW_DATA
WHERE RENTAL_ID NOT IN (SELECT RENTAL_ID FROM AIRBYTE_DATABASE.ANALYTICS.FACT_RENTAL_SNAPSHOT);

-- Verify table was created and populated
SELECT COUNT(*) AS RENTAL_COUNT FROM AIRBYTE_DATABASE.ANALYTICS.FACT_RENTAL_SNAPSHOT;

