INSERT INTO AIRBYTE_DATABASE.ANALYTICS.DIM_LOCATION (
    LOCATION_ID,
    ADDRESS_ID,
    ADDRESS,
    ADDRESS2,
    DISTRICT,
    CITY,
    COUNTRY,
    POSTAL_CODE,
    PHONE
)
SELECT
    ROW_NUMBER() OVER (ORDER BY A.ADDRESS_ID) + COALESCE((
        SELECT MAX(LOCATION_ID) FROM AIRBYTE_DATABASE.ANALYTICS.DIM_LOCATION
    ), 0) AS LOCATION_ID,
    A.ADDRESS_ID,
    A.ADDRESS,
    A.ADDRESS2,
    A.DISTRICT,
    CI.CITY,
    CO.COUNTRY,
    A.POSTAL_CODE,
    A.PHONE
FROM AIRBYTE_RAW_DATA.ADDRESS A
JOIN AIRBYTE_RAW_DATA.CITY CI ON A.CITY_ID = CI.CITY_ID
JOIN AIRBYTE_RAW_DATA.COUNTRY CO ON CI.COUNTRY_ID = CO.COUNTRY_ID
WHERE A.ADDRESS_ID NOT IN (
    SELECT ADDRESS_ID FROM AIRBYTE_DATABASE.ANALYTICS.DIM_LOCATION
);