MERGE INTO AIRBYTE_DATABASE.ANALYTICS.BI_RENTALS_ALL AS TARGET
USING (
  SELECT
    F.RENTAL_ID,
    F.CUSTOMER_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    C.CITY AS CUSTOMER_CITY,
    C.COUNTRY AS CUSTOMER_COUNTRY,

    F.STAFF_ID,
    S.STAFF_NAME,
    S.STORE_ID,
    S.STORE_ADDRESS,
    S.CITY AS STORE_CITY,
    S.COUNTRY AS STORE_COUNTRY,

    F.FILM_ID,
    FI.TITLE AS FILM_TITLE,
    FI.CATEGORY AS FILM_CATEGORY,
    FI.RELEASE_YEAR,
    FI.RATING,
    FI.LENGTH AS FILM_LENGTH,

    D.DATE_ID,
    D.FULL_DATE AS RENTAL_DATE,
    D.WEEKDAY AS RENTAL_WEEKDAY,

    F.RENTAL_DURATION,
    F.TOTAL_AMOUNT,
    F.CUSTOMER_RENTAL_RANK
  FROM AIRBYTE_DATABASE.ANALYTICS.FACT_RENTAL_SNAPSHOT F
  JOIN AIRBYTE_DATABASE.ANALYTICS.DIM_CUSTOMER_SCD C 
      ON F.CUSTOMER_ID = C.CUSTOMER_ID AND C.CURRENT_FLAG = TRUE
  JOIN AIRBYTE_DATABASE.ANALYTICS.DIM_FILM FI 
      ON F.FILM_ID = FI.FILM_ID
  JOIN AIRBYTE_DATABASE.ANALYTICS.DIM_DATE D 
      ON F.DATE_ID = D.DATE_ID
  JOIN AIRBYTE_DATABASE.ANALYTICS.DIM_STORE_STAFF S 
      ON F.STAFF_ID = S.STAFF_ID
) AS SOURCE
ON TARGET.RENTAL_ID = SOURCE.RENTAL_ID

WHEN NOT MATCHED THEN INSERT (
    RENTAL_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_CITY,
    CUSTOMER_COUNTRY,
    STAFF_ID,
    STAFF_NAME,
    STORE_ID,
    STORE_ADDRESS,
    STORE_CITY,
    STORE_COUNTRY,
    FILM_ID,
    FILM_TITLE,
    FILM_CATEGORY,
    RELEASE_YEAR,
    RATING,
    FILM_LENGTH,
    DATE_ID,
    RENTAL_DATE,
    RENTAL_WEEKDAY,
    RENTAL_DURATION,
    TOTAL_AMOUNT,
    CUSTOMER_RENTAL_RANK
)
VALUES (
    SOURCE.RENTAL_ID,
    SOURCE.CUSTOMER_ID,
    SOURCE.CUSTOMER_NAME,
    SOURCE.CUSTOMER_CITY,
    SOURCE.CUSTOMER_COUNTRY,
    SOURCE.STAFF_ID,
    SOURCE.STAFF_NAME,
    SOURCE.STORE_ID,
    SOURCE.STORE_ADDRESS,
    SOURCE.STORE_CITY,
    SOURCE.STORE_COUNTRY,
    SOURCE.FILM_ID,
    SOURCE.FILM_TITLE,
    SOURCE.FILM_CATEGORY,
    SOURCE.RELEASE_YEAR,
    SOURCE.RATING,
    SOURCE.FILM_LENGTH,
    SOURCE.DATE_ID,
    SOURCE.RENTAL_DATE,
    SOURCE.RENTAL_WEEKDAY,
    SOURCE.RENTAL_DURATION,
    SOURCE.TOTAL_AMOUNT,
    SOURCE.CUSTOMER_RENTAL_RANK
);
