-- DIM_DATE View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.DIM_DATE AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.DIM_DATE;

-- DIM_FILM View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.DIM_FILM AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.DIM_FILM;

-- DIM_STORE_STAFF View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.DIM_STORE_STAFF AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.DIM_STORE_STAFF;

-- DIM_LOCATION View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.DIM_LOCATION AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.DIM_LOCATION;

-- DIM_CUSTOMER_SCD View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.DIM_CUSTOMER_SCD AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.DIM_CUSTOMER_SCD;

-- FACT_RENTAL_SNAPSHOT View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.FACT_RENTAL_SNAPSHOT AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.FACT_RENTAL_SNAPSHOT;

-- FACT_PAYMENT View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.FACT_PAYMENT AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.FACT_PAYMENT;

-- BI_RENTALS_ALL View
CREATE OR REPLACE VIEW AIRBYTE_DATABASE.PRODUCTION.BI_RENTALS_ALL AS
SELECT * FROM AIRBYTE_DATABASE.ANALYTICS.BI_RENTALS_ALL;
