SET TEAM_ROLE = 'DEC';
SET TEAMMATE1_USER = 'ANTONI';
SET TEAMMATE1_PASSWORD = 'spain';
SET TEAMMATE2_USER = 'GRAHAM';
SET TEAMMATE2_PASSWORD = 'scotland';

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS IDENTIFIER($TEAM_ROLE);
GRANT ROLE IDENTIFIER($TEAM_ROLE) TO ROLE SYSADMIN;

-- Grants access to the AB warehouse
GRANT USAGE ON WAREHOUSE AIRBYTE_WAREHOUSE TO ROLE IDENTIFIER($TEAM_ROLE);

-- Grants access to the AB database
GRANT USAGE ON DATABASE AIRBYTE_DATABASE TO ROLE IDENTIFIER($TEAM_ROLE);

-- Grants access to the schema where Airbyte writes data
GRANT USAGE ON SCHEMA AIRBYTE_DATABASE.AIRBYTE_RAW_DATA TO ROLE IDENTIFIER($TEAM_ROLE);

GRANT SELECT ON ALL TABLES IN SCHEMA AIRBYTE_DATABASE.AIRBYTE_RAW_DATA TO ROLE IDENTIFIER($TEAM_ROLE);
GRANT SELECT ON FUTURE TABLES IN SCHEMA AIRBYTE_DATABASE.AIRBYTE_RAW_DATA TO ROLE IDENTIFIER($TEAM_ROLE);

-- create user for antoni
CREATE USER IF NOT EXISTS IDENTIFIER($TEAMMATE1_USER)
PASSWORD = $TEAMMATE1_PASSWORD
LOGIN_NAME = $TEAMMATE1_USER
DISPLAY_NAME = $TEAMMATE1_USER
DEFAULT_WAREHOUSE = 'AIRBYTE_WAREHOUSE'
DEFAULT_ROLE = $TEAM_ROLE
DEFAULT_NAMESPACE = 'AIRBYTE_DATABASE.AIRBYTE_RAW_DATA'
MUST_CHANGE_PASSWORD = TRUE;

-- create user for graham
CREATE USER IF NOT EXISTS IDENTIFIER($TEAMMATE2_USER)
PASSWORD = $TEAMMATE2_PASSWORD
LOGIN_NAME = $TEAMMATE2_USER
DISPLAY_NAME = $TEAMMATE2_USER
DEFAULT_WAREHOUSE = 'AIRBYTE_WAREHOUSE'
DEFAULT_ROLE = $TEAM_ROLE
DEFAULT_NAMESPACE = 'AIRBYTE_DATABASE.AIRBYTE_RAW_DATA'
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE IDENTIFIER($TEAM_ROLE) TO USER IDENTIFIER($TEAMMATE1_USER);
GRANT ROLE IDENTIFIER($TEAM_ROLE) TO USER IDENTIFIER($TEAMMATE2_USER);

SELECT 'Team user setup complete!' AS Status;
