-- setting airbyte credentials and warehouse

SET MY_USER = 'AIRBYTE_USER';
SET MY_PASSWORD = '123456789';
SET MY_ROLE = 'AIRBYTE_ROLE';
SET MY_WAREHOUSE = 'AIRBYTE_WAREHOUSE';
SET MY_DATABASE = 'AIRBYTE_DATABASE';
SET MY_SCHEMA = 'AIRBYTE_RAW_DATA';

USE ROLE ACCOUNTADMIN;

-- create airbyte roles --
CREATE ROLE IF NOT EXISTS IDENTIFIER($MY_ROLE);
GRANT ROLE IDENTIFIER($MY_ROLE) TO ROLE SYSADMIN;

-- create Airbyte user
CREATE USER IF NOT EXISTS IDENTIFIER($MY_USER)
PASSWORD = $MY_PASSWORD
LOGIN_NAME = $MY_USER
DISPLAY_NAME = $MY_USER
DEFAULT_WAREHOUSE = $MY_WAREHOUSE
DEFAULT_ROLE = $MY_ROLE
MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE IDENTIFIER($MY_ROLE) TO USER IDENTIFIER($MY_USER);

-- creating airbyte warehouse
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($MY_WAREHOUSE)
WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

-- creating airbyte databse and schema
CREATE DATABASE IF NOT EXISTS IDENTIFIER($MY_DATABASE);
USE DATABASE IDENTIFIER($MY_DATABASE);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($MY_SCHEMA);


-- granting warehouse usage airbyte user
GRANT USAGE ON WAREHOUSE IDENTIFIER($MY_WAREHOUSE) TO ROLE IDENTIFIER($MY_ROLE);

-- grant database usage
GRANT USAGE ON DATABASE IDENTIFIER($MY_DATABASE) TO ROLE IDENTIFIER($MY_ROLE);

-- Construct the fully qualified schema name first
SET MY_FULL_SCHEMA_NAME = $MY_DATABASE || '.' || $MY_SCHEMA;

-- Grant schema usage, table/stage creation using the constructed FQN variable
GRANT USAGE ON SCHEMA IDENTIFIER($MY_FULL_SCHEMA_NAME) TO ROLE IDENTIFIER($MY_ROLE);
GRANT CREATE TABLE ON SCHEMA IDENTIFIER($MY_FULL_SCHEMA_NAME) TO ROLE IDENTIFIER($MY_ROLE);
GRANT CREATE STAGE ON SCHEMA IDENTIFIER($MY_FULL_SCHEMA_NAME) TO ROLE IDENTIFIER($MY_ROLE);
GRANT CREATE SCHEMA ON DATABASE AIRBYTE_DATABASE TO ROLE AIRBYTE_ROLE;

-- check for status
SELECT 'Snowflake setup for Airbyte complete!' AS Status;
